Vagrant.configure("2") do |config|
    config.vm.box = "debian/bullseye64"
    config.vm.hostname = "azevix-srv-glpi"
    config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.provider "virtualbox" do |vb|
      vb.name = "azevix-srv-glpi"
      vb.memory = "2048"
      vb.cpus = 2
    end
  
    config.vm.provision "shell", path: "provision.sh"
  end
  